handler/oauth2/flow_refresh.go, handler/oauth2/flow_refresh_test.go
* handler/oauth2/refresh: requestedAt time is not reset - closes #109
* handler/oauth2/refresh: session is not transported to new access token - closes #108
=> handler/oauth2: resolve issues with refresh token flow

authorize_error.go, authorize_error_test.go
Hi!
According [rfc](https://tools.ietf.org/html/rfc6749#section-4.2.2.1) in implicit flow all error parameters should be placed to the fragment component of the redirection url.
=> oauth2/implicit: fix redirect url on error

request.go
SetRequestedScopes actually appended.
=> Request: fix SetRequestedScopes

access_request_handler.go
=> oauth2: basic auth should decode client id and secret

handler/openid/flow_hybrid_test.go, handler/openid/strategy_jwt.go, handler/openid/strategy_jwt_test.go
Provides the fixes in #163 because I'm impatient 😛
=> handler/openid: remove forced nonce

handler/openid/flow_refresh_token.go, handler/openid/flow_refresh_token_test.go, session_test.go, token/jwt/claims.go, token/jwt/claims_test.go
=> handler/openid: only refresh id token with id_token response type

errors.go, handler/openid/strategy_jwt.go, handler/openid/strategy_jwt_test.go, integration/oidc_explicit_test.go, integration/oidc_implicit_hybrid_test.go, token/jwt/claims_id_token.go, token/jwt/claims_id_token_test.go
Fosite is now capable of detecting authorization flows that
are not conformant with the OpenID Connect spec.
=> Adds ability to catch non-conform OIDC authorizations

handler/oauth2/flow_authorize_code_token.go, session.go
Fixes one wrong comment and extends another.
=> Small comment fixes

scope_strategy.go, scope_strategy_test.go
The ExactScopeStrategy performs a simple string match (case sensitive)
of scopes.
=> core: Adds ExactScopeStrategy

HISTORY.md, compose/compose.go, compose/compose_openid.go, compose/compose_strategy.go, handler/openid/flow_explicit_auth_test.go, handler/openid/flow_hybrid.go, handler/openid/flow_hybrid_test.go, handler/openid/flow_implicit.go, handler/openid/flow_implicit_test.go, handler/openid/strategy_jwt.go, handler/openid/validator.go, handler/openid/validator_test.go, integration/oidc_explicit_test.go, token/jwt/header.go, token/jwt/jwt.go
This patch improves the OIDC prompt, max_age, and id_token_hint
validation.
=> openid: Improves prompt, max_age and id_token_hint validation

Gopkg.lock, Gopkg.toml, handler/oauth2/strategy_jwt_test.go, handler/openid/strategy_jwt.go, token/jwt/claims_id_token.go, token/jwt/claims_id_token_test.go, token/jwt/claims_jwt.go, token/jwt/claims_jwt_test.go
=> jwt: Sets audience to a string array

client_authentication.go
Signed-off-by: arekkas <aeneas@ory.am>
=> Improve token_endpoint_auth_method error message

hash_bcrypt_test.go
https://github.com/ory/hydra/pull/1052#discussion_r220323735
=> fosite: use test tables for Hasher unit tests

HISTORY.md, handler/oauth2/introspector_jwt.go, handler/oauth2/strategy.go, handler/oauth2/strategy_jwt.go, handler/openid/flow_explicit_auth.go, handler/openid/flow_hybrid.go, handler/openid/flow_implicit.go, handler/openid/validator.go, handler/openid/validator_test.go
Signed-off-by: Prateek Malhotra <someone1@gmail.com>
=> eliminate hanging context.TODO() to properly propagate context [closes #307]

handler/openid/flow_explicit_auth_test.go, handler/openid/flow_explicit_token.go, handler/openid/flow_explicit_token_test.go, handler/openid/flow_refresh_token.go, handler/openid/flow_refresh_token_test.go, handler/openid/helper.go, handler/openid/helper_test.go
#1085 in ory/hydra
When request access_token with "grant_type=authorization_code", the id_token of response has not "at_hash" claim. It is optional but FAPI(https://openid.net/specs/openid-financial-api-part-2.html#authorization-response-parameter-injection-attack) use it to prevent some attack.
This PR try to add at_hash.
force push.
=> Append Access Token Hash to ID Token

handler/openid/flow_hybrid.go, handler/openid/flow_hybrid_test.go
* none
* Should set authorize code's expires_at, which is issued by hybrid flow.
force push.
* Tested for hybrid flow with PCKE enabled (fixed by https://github.com/ory/fosite/pull/328).
=> should set expires at for authorize code issued by hybrid flow

authorize_request_handler.go, introspection_request_handler.go
https://github.com/ory/fosite/issues/352#issuecomment-484376760
Allow users to set error message with `WithDebug()` when `invalid_client` occurs.
force push.
=> allow add debug log to invalid_client error for authorize request

.github/ISSUE_TEMPLATE/bug_report.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Signed-off-by: aeneasr <aeneas@ory.sh>
force push.
=> docs: Updates issue and pull request templates

fosite.go, oauth2.go
None. (To stretch a point, #323 )
I appreciate great product, and I use this repository in my OAuth2.0 server.
I read codes in this repository, and I found some miss document comments. So, I fix it. I would appreciate it if you could check this PR.
force push.
- My changes is in only comments.
=> docs: Fix method/struct documents

request.go, request_test.go
=> fix: Merge request ID as well

handler/oauth2/flow_refresh.go, handler/oauth2/flow_refresh_test.go
=> fix: handle txn serialization errors that can be thrown by call to 'Commit'

client.go, oauth2.go
Fixed some typos I have found while auditing the code.
=> fix: Fixed various typos

CONTRIBUTING.md
=> docs: Using Slack now

storage/memory.go
Followup to https://github.com/ory/fosite/pull/417.
I just realized that I think this is not needed as well.
=> fix: Further cleanup of memory storage

oauth2.go
Fixed comments, Changed GetSession to SetSession.
=> fix: Fix GetSession comments

CONTRIBUTING.md
Signed-off-by: aeneasr <aeneas@ory.sh>
=> docs: update github templates

handler/oauth2/flow_authorize_code_token.go, handler/oauth2/flow_authorize_code_token_test.go
No prior discussion, but this is somewhat related to #370, which makes it possible for clients to be issued a refresh token without requesting a scope.
There may be clients which may not be allowed to use the `refresh_token` grant type, but which will currently be issued a refresh token during the authorization code flow. Disallowing the refresh_token grant type might be particularly common when there are public clients (using this flow with PKCE).
It is impossible to use the issued refresh token when the client does not have the grant type, and no other client can use it either. It would be neater to avoid issuing refresh tokens that cannot be used.
A look at the OAuth 2.0 and OpenID Connect specs shows nothing particularly relevant, except RFC 6749's:
> Issuing a refresh token is …
=> fix: Do not issue refresh tokens that can't be used

access_request_handler.go, authorize_request_handler.go, helper.go, introspection_request_handler.go
A very small change just to expose this method because I need for my own parsing of scopes and no point in duplicating it.
the changes.
=> feat: Making RemoveEmpty public

compose/compose_strategy.go
I realized those are missing.
This now completes support for ES256.
=> feat: New compose strategies for ES256

access_write.go, authorize_error.go, authorize_error_test.go, authorize_write.go, authorize_write_test.go, revoke_handler.go
Fixing tests I broke with https://github.com/ory/fosite/pull/465.
Also found out that there are few better places for setting those headers. So fixed that as well.
the changes.
=> fix: No cache headers followup

storage/memory.go
None.
We use memory storage for unit tests. We have observed that occasionally tests fail because of concurrent access to maps making tests flaky. This PR makes memory storage more robust and support concurrent access to it.
the changes.
=> feat: Added locking to memory storage

.nancy-ignore
=> fix: ignore x/net false positives

README.md
Missing `.` in readme in the contributing section
Just added the missing dot
the changes.
No further comments tiny PR
=> fix: added missing dot

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Updated repository templates to https://github.com/ory/meta/commit/01a6e59075cbe305ebd179bbaa9e76129b791337.
=> chore: update repository template to 01a6e590

authorize_helper.go
=> fix: return allowed redirect url with preference

handler/openid/validator_test.go
I think better descriptions.
the changes.
=> docs: Improved test descriptions

authorize_request_handler.go, client_authentication_jwks_strategy.go, handler/oauth2/flow_refresh.go, handler/openid/strategy_jwt.go, handler/openid/validator.go
* Do not leak potentially internal error messages directly but only through debugging messages.
* Improved some language in error messages.
the changes.
=> feat: Better error messages

.github/workflows/oidc-conformity.yml, handler/openid/flow_explicit_token.go
=> ci: add oidc conformity tests

authorize_request_handler.go
Just a tiny change to have less copy-pasting.
the changes.
=> refactor: Use constructor

.github/workflows/oidc-conformity.yml
the changes.
works.
appropriate).
=> Fix conformity test issues

.github/workflows/oidc-conformity.yml, Makefile
the changes.
works.
appropriate).
=> ci: use correct fork and hash for conformity testing

token/jwt/token.go, token/jwt/token_test.go
#606 
the changes.
works.
appropriate).
=> feat: include typ header

handler/openid/storage.go, storage/memory.go
Fixes #538.
the changes.
works.
appropriate).
=> docs: Document that DeleteOpenIDConnectSession is deprecated

compose/compose.go, compose/config.go
Support FormPostHTMLTemplate configuration during fosite init phase
https://github.com/ory/fosite/issues/646
the changes.
works.
appropriate).
=> feat: Support FormPostHTMLTemplate config for fosite

handler/oauth2/flow_refresh.go, handler/oauth2/flow_refresh_test.go
https://github.com/ory/hydra/issues/3004
the changes.
works.
appropriate).
=> fix: Handle token_inactive error for multiple concurrent refresh requests

token/hmac/hmacsha.go, token/hmac/hmacsha_test.go
Add `Hash func() hash.Hash` field in `hmac.HMACStrategy` to allow using a custom `hash.Hash` function. When nil, the default `sha512.New512_256` is used.
https://github.com/ory/fosite/issues/654
the changes.
works.
appropriate).
=> feat:  Use custom hash.Hash in hmac.HMACStrategy

handler/oauth2/flow_refresh.go, handler/oauth2/flow_refresh_test.go
When trying to use an expired refresh token, return invalid_grant.
https://github.com/ory/fosite/issues/645
the changes.
works.
appropriate).
=> fix: handle invalid_token error for refresh_token is expired

client_authentication_jwks_strategy.go, client_authentication_jwks_strategy_test.go
vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the
maintainers to push the changes.
=> feat: make http source contextualized

.github/workflows/oidc-conformity-master.yml, .github/workflows/oidc-conformity.yml
=> ci: move conformity tests to hydra v2.x

handler/openid/strategy_jwt.go, token/jwt/claims_id_token.go, token/jwt/header.go
This change adds json mappings to `DefaultSession` type and its contents to use in enriching the refresh webhook in Hydra here https://github.com/ory/hydra/pull/3204
=> feat: add json mappings to default session and its contents

integration/authorize_code_grant_test.go, session.go
Fix: this change fixes integration test that was broken in https://github.com/ory/fosite/pull/687.
=> fix: add json mappings to generic session to fix tests

integration/authorize_code_grant_test.go, session.go
This change is the same as https://github.com/ory/fosite/pull/689 to prevent issues in the tests once https://github.com/ory/fosite/pull/684 is backported to master.
=> feat: add json mappings to generic session to match openid session

.circleci/config.yml
This reverts commit 2eea63bddcbdf50771adf670391e495e339f619f. There are quite a few CircleCI tasks that now break.
If this pull request addresses a security vulnerability,
=> chore: revert "delete .circleci folder (#699)"

.github/workflows/oidc-conformity-master.yml
=> ci: use hydra main branch

config.go, config_default.go, token/hmac/hmacsha.go
BREAKING CHANGE: `GetGlobalSecret` and `GetRotatedGlobalSecrets` signatures changed and it is now possible to add an error.
=> refactor: allow secret configuration to return errors

README.md
The README example is not up to date
=> fix: quick start secret config

HISTORY.md
Fix a broken link to the `CHANGELOG.md` file in the `HISTORY.md` file.
=> fix: fix broken link in History.md

CHANGELOG.md
=> docs: CHANGELOG.md is not used anymore
