.travis.yml
Happy New Year,
This change adds additional builds to the build matrix.
Go version 1.2 and 1.3 are still supported by Ubuntu 14.04 LTS.
So, even though go users tend to use the latest stable it would
be nice to know at a glance that this library is passing for legacy
users.
Go tip has also been added and placed under allowed failures for
bleeding edge users as well.
=> Added more go versions to build matrix

handler/core/client/client.go, handler/core/explicit/explicit_token.go, handler/core/owner/owner.go, handler/core/refresh/refresh.go
When retrieving an auth code, you can optionally set the ```TokenSession.Extra``` data to store additional data like a user id that was stored when you created the authorization code. That session data should be available in ```CreateAccessTokenSession``` and ```CreateRefreshTokenSession```, but it ends up coming through nil.
This pull request ensures that session data passes through to the access token and refresh token so you can -- at the very least -- associate user ids with the access/refresh tokens.go in your storage implementation.
=> Include user session data in all calls to storage handlers

README.md
Someone forgot to rename the variable name when copy-pasting in the example.
Signed-off-by: Kim Johansson <kim@kumiko.se>
=> docs: define implicitHandler

README.md
The README url to the suggested example was broken.
=> Clean-up fosite-example/main.go link in README.md

handler/core/strategy/jwt.go, handler/core/strategy/jwt_test.go
Validate token function only return error by [interface definition](https://github.com/ory-am/fosite/blob/dfb047d/handler/core/strategy.go), but in jwt strategy return both signature and error.
=> fix jwt strategy interface mismatch

authorize_helper.go, handler/core/explicit/explicit_auth.go, handler/core/explicit/explicit_auth_test.go, handler/core/implicit/implicit.go, handler/oidc/explicit/explicit_auth.go, handler/oidc/hybrid/hybrid.go, handler/oidc/implicit/implicit.go
=> oauth2: implicit handlers do not require tls over https

glide.lock, glide.yaml, handler/oauth2/strategy_jwt.go, handler/openid/strategy_jwt.go, token/jwt/claims.go, token/jwt/claims_id_token.go, token/jwt/claims_id_token_test.go, token/jwt/claims_jwt.go, token/jwt/claims_jwt_test.go, token/jwt/header.go, token/jwt/jwt.go, token/jwt/jwt_test.go
This PR is in direct response to #76.
NOTE:
No direct breaking API changes should have been introduced in this pull request, as long as no one explicitly uses the raw values of "iat", "exp" and "nbf" claims (was int, is now float). This is due to the fact that jwt-go needs float64 types when validating the claims. I will create a new PR to jwt-go as well that is going to allow int64 values to be parsed. Hopefully it will get merged fast. If that's the case, after a minor upgrade to fosite removing the float64 casts, nothing API-wise will have changed since before the upgrade to jwt-go 3.0.0. 
// Alex
=> Updated: jwt-go is now v3.0.0.

handler/oauth2/validator.go
Someone left them probably while debugging something...
=> Removed unnecessary logging

compose/compose_oauth2.go, fosite-example/main.go, handler/oauth2/flow_refresh.go, handler/oauth2/flow_refresh_test.go, handler/oauth2/flow_resource_owner.go, handler/oauth2/flow_resource_owner_storage.go, handler/oauth2/flow_resource_owner_test.go, internal/oauth2_owner_storage.go, request_test.go
I'm currently porting over some old authentication services with fosite and have ran into the issue specified here: https://github.com/ory-am/fosite/issues/78
Where internal clients will make use of the password grant type along with the access / refresh tokens.
There was a comment suggesting that this particular feature be added as a separate PR than the issue raised; and since it's been around a month with no updates I decided to give it a go.
Please let me know if anything doesn't meet the RFC or needs changes.
=> oauth2: added refresh token generation for password grant type

handler/oauth2/strategy_jwt.go, handler/oauth2/strategy_jwt_test.go
Fixes https://github.com/ory-am/fosite/issues/120. The JWT strategy now uses the `ExpiresAt` map introduced in `0.5.0` to set expirations by `fosite.TokenType`. Previously the expiration was the same for all token types based on the `JWTClaims.ExpiresAt` field.
Signed-off-by: Cristian Graziano <cristiangraz@users.noreply.github.com>
=> handler/oauth2: set JWT ExpiresAt claim per TokenType from the session

introspection_response_writer.go
This PR improves the behavior of the OAuth2 Introspection endpoint to respond with a more appropriate error message when the request is invalid. Currently, fosite responds to all requests other than those that are classified as "unauthorized" with an HTTP status code of 200 and body of `{"active":"false"}`.
While the spec doesn't define what to do in the case of an invalid request (at least not that I could find), I can't think of a reason that one would want to obscure the difference between an invalid request and some other kind of error. It definitely has the potential to be confusing though when one is developing an application! We ran into this case when accidentally using `GET` instead of `POST` on this endpoint.
[1] https://tools.ietf.org/html/rfc7662#section-2.3
=> Introspection endpoint responds to invalid requests appropriately

token/jwt/claims.go
This commit allows `aud` to be passed in as a single element array
during consent validation on Hydra. This fixes
https://github.com/ory-am/hydra/issues/314.
Signed-off-by: Son Dinh <son.dinh@blacksquaremedia.com>
=> token/jwt: Allow single element string arrays to be treated as strings

README.md
This was causing the link to lead to a non-existing page.
=> Fix missing protocol in README

access_error_test.go, errors.go
Section 5.2 specifies the parameters for access error responses; the "error" and "error_description" parameters are misnamed ("name" and "description").
https://tools.ietf.org/html/rfc6749#section-5.2
The patch maintains backwards compatibility by marshaling both the existing fields, and the fields required by the RFC.
=> RFC6749Error: conform to RFC 6749

revoke_handler.go, revoke_handler_test.go
Allow public clients to revoke tokens with just a Client ID.
This functionality is described in the OAuth2 spec here: https://tools.ietf.org/html/rfc7009#section-5
Relevant issue: #136
=> Public Client Token Revocation

authorize_helper_test.go, compose/compose.go, compose/compose_oauth2.go, handler/oauth2/introspector_jwt.go, handler/oauth2/introspector_jwt_test.go, handler/oauth2/strategy.go, handler/oauth2/strategy_jwt.go, handler/oauth2/strategy_jwt_test.go, integration/helper_endpoints_test.go, integration/helper_setup_test.go, integration/introspect_token_test.go, token/jwt/claims_jwt.go, token/jwt/claims_jwt_test.go, token/jwt/jwt.go
Conversation started in #140. A quick draft was requested by @arekkas, which I provided there, but I figured starting a review might be a better way to talk about the code than inline code blocks and patch files. I won't be offended if this isn't consistent with the roadmap. The functionality is either going into my application code or fosite, so it's time well spent either way.
The goal here is to be able to perform validation of JWT access tokens without hitting the storage backend.
Without too much effort, we can define an introspector to do it. No public symbols or behavior are changed. Just added a few things that make this nicer.
=> handler/oauth2: allow stateless introspection of jwt access tokens

authorize_helper.go, authorize_helper_test.go
=> authorize: allow localhost subdomains such as blog.localhost:1234

README.md, handler/oauth2/introspector_jwt.go
RevokeHandler has been removed because it conflicts with Stateless JWT
accesstokens and revocable hmac refresh tokens. The readme has been
updated to warn users about possible misconfiguration.
Closes [154](https://github.com/ory/fosite/issues/154)
=> Removes RevokeHandler from JWT Introspector

introspect.go, introspect_test.go
As discussed on Gitter some time ago - fosite needs to use _access_token_ query param. (https://tools.ietf.org/html/rfc6750)
=> Get the token from the access_token query parameter

access_request_handler.go
=> oauth2: basic auth should www-url-decode client id and secret

handler/oauth2/flow_authorize_implicit.go
There is no expire date set on implicit token flows.
The expire date is updated to the session after the store function is called.
=> no expire date is set to session when storing token to storage.

handler/oauth2/flow_authorize_code_auth.go
Authorize code expire time is set after the calling CreateAuthorizeCodeSession.
This way i cannot store the expire time in the database.
This is the same kinda issue as with the implicit code session expire time (other PR)
=> authorize code expire time isset after persist

access_request_handler.go, access_request_handler_test.go, authorize_request_handler.go, authorize_request_handler_test.go, client_manager.go, internal/storage.go, introspection_request_handler.go, revoke_handler.go, revoke_handler_test.go, storage/memory.go
added context to client storage GetClient signature.
See issue ory/fosite#161
=> added context to GetClient storage interface, see issue: ory/fosite#161

compose/compose.go, integration/authorize_code_grant_test.go, integration/authorize_implicit_grant_test.go, integration/client_credentials_grant_test.go, integration/introspect_token_test.go, integration/refresh_token_grant_test.go, integration/resource_owner_password_credentials_grant_test.go, integration/revoke_token_test.go
Makes it a little easier for composing, plus follows the same conventions as storage. Seeks to keep compatibility by setting BCrypt as the default hasher if one isn't set.
Signed-off-by: Matthew Hartstonge <matt@mykro.co.nz>
=> Enable fosite composing with custom hashers.

handler/oauth2/flow_authorize_code_token.go
Hi!
JWT access token does not contain any granted scopes in "scp" claim. This is because the access token is generated before the scopes are granted.
=> handler/oauth2: grant scopes before the access token is generated

CONTRIBUTING.md, README.md
Running `go test ./...` fails, even with everything installed. Travis seems to be running the equivalent of `go test $(glide novendor)` and this is what Hydra is doing, so I'm assuming this is more correct.
=> Update test command in README and CONTRIBUTING

HISTORY.md, handler/oauth2/introspector.go, handler/oauth2/introspector_test.go
Removes authorize code introspection in the HMAC-based strategy and now checks scopes of refresh tokens as well.
=> oauth2/introspector: remove auth code, refresh scopes

README.md
It seems that the documentation was declaring as OAuth2Provider the variable `oauth2Provider` whereas it used a non-declared variable `oauth2`. I renamed `oauth2` into the variable declared `oauth2Provider`.
Furthermore, on line 333, the IntrospectToken method was called without the TokenType argument. I added the fosite.AccessToken type.
=> Fixing documentation oauth2 variable + old method

compose/compose_oauth2.go, compose/config.go, handler/oauth2/introspector.go, handler/oauth2/introspector_test.go
My attempt to make the core validator configurable refer to #207. If you agree on the direction I'll write tests for the case that `AccessOnly` is turned on.
=> Configure core validator with access only option

handler/oauth2/flow_resource_owner.go, handler/oauth2/flow_resource_owner_test.go
Noticed that expires at is not set in the session by default unlike the authorize code, client credential and refresh flows.
=> Set expires at for password credentials flow

handler/oauth2/flow_authorize_implicit.go
Hi!
JWT access token has invalid value in "exp" claim if implicit flow is used. This is because the token is generated before it is assigned an expiration time.
=> handler/oauth2: set expiration time before the access token is generated

introspection_request_handler.go, introspection_request_handler_test.go, storage/memory.go
Signed-off-by: Dmitry Dolbik <dolbik@gmail.com>
Introspection handler does not decode a valid encoded username and password on Basic Authorization process.
For example access_request_handler Basic Authorization parameters decoded properly
Basic Authorization behaviour of endpoints should be the same i think
=> Introspection: Decode of Basic Authorization username/password

introspection_response_writer.go
The introspection response writer was missing `application/json`
in header `Content-Type`. This patch fixes that.
Closes #209
=> introspection: Adds missing http header to response writer

LICENSE, README.md, compose/compose.go, compose/compose_pkce.go, compose/config.go, errors.go, handler/pkce/handler.go, handler/pkce/handler_test.go, integration/authorize_code_grant_public_client_pkce_test.go, integration/authorize_code_grant_public_client_test.go, integration/helper_endpoints_test.go, integration/helper_setup_test.go
This change adds [PKCE](https://tools.ietf.org/html/rfc7636) support for methods none and S256 and adds it per default to the composer with forced PKCE and method none disallowed. These settings can be configured using `compose.Config.AllowPublicAuthCodeFlowWithoutPKCE` and `compose.Config.EnablePKCEPlainChallengeMethod`.
Closes #213
To do:
=> handler: Adds PKCE implementation for none and S256

request.go, request_test.go
The sanitize request method introduced a change where the generated ID for an access token and refresh token are different for the same response.
This is due to the ID being generated on the sanitized request not being passed back to the handler e.g. https://github.com/ory/fosite/blob/master/handler/oauth2/flow_refresh.go#L110.
To mitigate this the request ID is pre-generated on the original requester. There may be a better approach that would also pass the test.
=> Regression fix for request ID in refresh token flow

Gopkg.lock, compose/compose_openid.go, compose/config.go, handler/openid/flow_explicit_auth.go, handler/openid/flow_explicit_auth_test.go, handler/openid/flow_hybrid.go, handler/openid/flow_hybrid_test.go, handler/openid/flow_implicit.go, handler/openid/flow_implicit_test.go, handler/openid/validator.go, handler/openid/validator_test.go, handler/pkce/storage.go, integration/authorize_code_grant_public_client_pkce_test.go
The validator, for now, validates the prompt parameter of OIDC requests.
=> openid: Adds a validator used to validate OIDC parameters

access_request_handler.go, authorize_request_handler.go, integration/helper_endpoints_test.go, introspect.go, introspection_request_handler.go, revoke_handler.go
Use Multipart form parse function as some client implementations use it to send form data.
e.g All of our native clients which use CURL
=> Treat posted data as multipart

HISTORY.md, handler/openid/flow_explicit_auth.go, handler/openid/flow_explicit_auth_test.go, handler/openid/flow_explicit_token.go, handler/openid/flow_explicit_token_test.go, handler/openid/flow_refresh_token.go, handler/openid/flow_refresh_token_test.go
Before this patch, the `id_token` response type was required whenever an ID Token was requested. This patch changes that.
=> openid: Do not require id_token response type for auth_code

compose/compose.go, compose/compose_strategy.go, compose/config.go, handler/openid/flow_explicit_token_test.go
Resolves an issue where expiry and issuer where not properly configurable in the strategy.
See https://github.com/ory/hydra/issues/985
=> compose: Pass ID Token configuration to strategy

compose/config.go
=> compose: fix Config.GetHashCost godoc comment

compose/config.go, hash_bcrypt.go, hash_bcrypt_test.go
Users of this library could easily create the following:
```Go
hasher := fosite.BCrypt{}
hasher.Hash(..)
```
This is a problem because `WorkFactor` will default to 0 and `x/crypto/bcrypt` will default that to 4 (See https://godoc.org/golang.org/x/crypto/bcrypt). Instead this should be some higher cost factor.
I didn't use `config.GetHashCost()` because that's in another package. 
Callers who need a lower WorkFactor can still lower the cost, if needed.  
amend the commit, you might need to force push using `git push --force …
=> raise bcrypt cost factor lower bound to x/crypto/bcrypt default

HISTORY.md, Makefile, handler/oauth2/strategy_jwt.go, token/jwt/claims_jwt.go
The interface needed to change in order to natively handle the audience claim.
=> oauth2: Update jwt access token interface

authorize_request_handler.go, authorize_request_handler_oidc_request_test.go, client.go, client_authentication.go, client_authentication_jwks_strategy.go, client_authentication_jwks_strategy_test.go, client_authentication_test.go, compose/compose_oauth2.go, handler/oauth2/flow_authorize_code_token_test.go, handler/oauth2/flow_refresh.go, handler/oauth2/flow_refresh_test.go, handler/openid/strategy_jwt.go, handler/openid/validator.go, integration/helper_endpoints_test.go, integration/refresh_token_grant_test.go, introspection_response_writer.go, token/jwt/claims_id_token.go, token/jwt/claims_jwt.go, token/jwt/header.go, token/jwt/jwt.go
This patch resolves several issues regarding the refresh flow. First,
an issue has been resolved which caused the audience to not be
set in the refreshed access tokens.
Second, scope and audience are validated against the client's
whitelisted values and if the values are no longer allowed,
the grant is canceled.
Closes #331
Closes #325
Closes #324
=> oauth2: Improve refresh security and reliability

introspection_response_writer.go, introspection_response_writer_test.go
* None
* Make sure `exp` will be omitted if `GetExpiresAt(AccessToken)` is nil or zero value (no expiration)
* Currently, even if `GetExpiresAt(AccessToken)` is zero value, Unix() will be called, and `ExpiresAt` will be set to `-62135596800` because golang's zero time is `0001-01-01T00:00:00Z` but not `1970-01-01T00:00:00Z`
force push.
* Currently, even if we introspect RefreshToken, AccessToken's ExpiresAt will be …
=> do omit exp if ExpiresAt is zero value

HISTORY.md, compose/compose_oauth2.go, compose/compose_openid.go, compose/compose_strategy.go, compose/config.go, handler/oauth2/flow_authorize_code_auth.go, handler/oauth2/flow_authorize_code_token.go, handler/oauth2/flow_authorize_code_token_test.go, handler/oauth2/flow_authorize_implicit.go, handler/oauth2/flow_refresh.go, handler/oauth2/flow_refresh_test.go, handler/oauth2/flow_resource_owner.go, handler/oauth2/flow_resource_owner_test.go, handler/oauth2/helper.go, handler/oauth2/strategy_hmacsha.go, handler/oauth2/strategy_hmacsha_test.go, handler/oauth2/strategy_jwt_test.go, handler/openid/flow_hybrid.go, handler/openid/flow_hybrid_test.go, integration/oidc_implicit_hybrid_public_client_pkce_test.go, integration/refresh_token_grant_test.go
Set it to `-1` to disable this feature. Defaults to 30 days.
=> oauth2: Add ability to specify refresh token lifespan

README.md
The TokenIntrospection example in the README is slightly inaccurate and misleading; the session data will need to come from the returned AccessRequester, not the pre-created session. The session passed to IntrospectToken isn't mutated.
=> update to the Introspection example in the documentation

revoke_handler.go, revoke_handler_test.go
https://github.com/ory/fosite/issues/379
This commit modifies the case for ErrInvalidRequest in
WriteRevocationResponse to respect the 400 error code
and not fallthrough to ErrInvalidClient.
=> revoke_handler: respecting ErrInvalidRequest code

README.md, compose/compose_oauth2.go, compose/config.go, handler/oauth2/flow_authorize_code_auth.go, handler/oauth2/flow_authorize_code_token.go, handler/oauth2/flow_authorize_code_token_test.go, handler/oauth2/flow_refresh.go, handler/oauth2/flow_refresh_test.go, handler/oauth2/flow_resource_owner.go, handler/oauth2/flow_resource_owner_test.go
Original discussion #370 discussed with @aeneasr
This adds the `RefreshTokenScopes` to compose config to set which scopes will provide a refresh token on grant exchange. This defaults to "offline" and "offline_access". When empty all grant exchanges will provide a refresh token.
=> Add RefreshTokenScopes Config

compose/config.go, handler/pkce/handler.go, revoke_handler.go, revoke_handler_test.go
#1512
@aeneasr 
Remove the checks in PKCE flow that limits the feature to Public clients only.
=> Enable PKCE for private clients

authorize_request_handler.go, authorize_request_handler_test.go
https://github.com/ory/hydra/issues/1642
@aeneasr 
Changing where the state parameter is saved to the AuthorizeRequester so it can be used and returned in error conditions.
=> Fix for ory/hydra#1642. Return state parameter in authorization error

README.md
Just noticed that `fosite.ExactScopeStrategy` is not documented, so here it is.
=> docs: add undocumented ExactScopeStrategy

arguments.go, arguments_test.go, authorize_error.go, handler/oauth2/flow_authorize_code_auth.go, handler/oauth2/flow_authorize_code_token.go, handler/oauth2/flow_authorize_implicit.go, handler/oauth2/flow_client_credentials.go, handler/oauth2/flow_refresh.go, handler/oauth2/flow_resource_owner.go, handler/openid/flow_explicit_auth.go, handler/openid/flow_explicit_token.go, handler/openid/flow_implicit.go, handler/openid/flow_refresh_token.go, handler/pkce/handler.go
Previously Arguments.Exact had vague semantic where
it coudln't distinguish between value with a space and multiple
values. Split it into 2 functions with clear semantic.
Old .Exact() remains for compatibility and marked as deprecated
=> fosite.Arguments: Nano optimization of .Exact()

authorize_helper.go, authorize_helper_test.go
This implements support for a dynamic port request from an oauth2 client.
RFC reference: https://tools.ietf.org/html/rfc8252#section-7.3
#284
https://github.com/ory/hydra/issues/1732
The RFC (https://tools.ietf.org/html/rfc8252#section-7.3) states an URI like `http://127.0.0.1:{port}/{path}` and `http://[::1]:{port}/{path}`. I am not 100% sure if this is a must or just a regex example. 
I have implemented this in fosil that it is now possible to register:
* http://127.0.0.1
* http://[::1]
... and if a registered client has one or both of these redirect uri's a client may request a dynamic port onto the loopback interface. For example …
=> RFC8252#section-7.3 Loopback Interface Redirection

errors.go, handler/oauth2/flow_refresh.go, handler/oauth2/flow_refresh_test.go
- https://github.com/ory/hydra/issues/1719
- https://github.com/ory/hydra/issues/1735 
https://github.com/ory/hydra/pull/1766
The `hydra` PR has integration test that verifies the end-to-end flow is working as indented. It relies on the API changes introduced here to function.
This commit provides the functionality required to address:
- https://github.com/ory/hydra/issues/1719
- https://github.com/ory/hydra/issues/1735 
This has been accomplished by:
- Adding a new error type `ErrSerializationFailure` which an authorization service is expected to wrap and return from its respective storage implementation in the event that it encounters an error due to concurrent access.
- Adding error checking to the `RefreshTokenGrantHandler`'s `PopulateTokenEndpointResponse` method so it can deal with …
=> fix: handle transactional errors due to concurrent updates in the refresh token grant handler

storage/memory.go
#346  Proposed changes
`DeleteAuthorizeCodeSession` and `CreateImplicitAccessTokenSession` not part of any storage interface. So deleting them to not confuse people to think they have to implement them.
=> fix: Not part of any interface

client.go, storage/memory.go
#304
List all possible combinations in the example response types in example memory store. This really tripps novice users of this library.
=> fix: List all response types in example memory store

handler/oauth2/flow_authorize_code_token.go, handler/oauth2/flow_authorize_code_token_test.go, handler/oauth2/flow_refresh.go, handler/oauth2/flow_refresh_test.go
#418 
Refresh token flow has been changed in order to return invalid_grant instead of invalid_request when there is a client mismatch or when the refresh token has not been found.
Authorization code flow has been changed in order to return invalid_grant instead of invalid_request when there is a client mismatch or the redirect uri doesn't match the one from the authorization request (or is empty). 
the changes.
=> fix: return invalid_grant instead of invalid_request according to rfc6749#section-5.2

handler/oauth2/flow_authorize_code_token.go, handler/oauth2/flow_authorize_code_token_test.go, handler/oauth2/flow_refresh.go, handler/oauth2/flow_refresh_test.go
Return invalid_grant instead of invalid_request when in authorization code flow when the user is not the owner of the authorization code or if the redirect uri doesn't match from the authorization request.
the changes.
=> fix: return invalid_grant instead of invalid_request in refresh flow

compose/compose_pkce.go, compose/config.go, handler/pkce/handler.go, handler/pkce/handler_test.go
Alternative proposal for the issue discussed in #389 and #391, where enforcement of PKCE is wanted only for certain clients.
Add a new flag `EnforcePKCEForPublicClients` which enforces PKCE only for public clients. The error hint is slightly different, as it mentions PKCE is enforced for "this client" rather than "clients". (It intentionally does not mention why it's enforced, as I think basing it on public clients is an implementation detail that servers may want to change without adding to the error hints)
I didn't use an enum, as suggested in #391, because I imagine it would be a backwards compatibility problem. I could be convinced otherwise.
=> feat: Add a flag to enforce PKCE only for public clients

arguments.go, arguments_test.go
Signed-off-by: Matthew Hartstonge <matt@mykro.co.nz>
There was a logic bug in `Arguments.MatchesExact(...items)`, where it would never return true and was untested.
the changes.
I also shortcut the processing of `Matches`, so you don't have to process a match if the lengths of arguments and items differ.
=> fix(arguments): fixes a logic bug in MatchesExact and adds documentation

client_authentication.go, client_authentication_test.go
I noticed that client credentials are URL-decoded after being extracted from the POST body form, which was already URL-decoded by Go. The accompanying error message suggests this was copied and pasted from the HTTP basic authorization header handling, which is the only place where the extra URL-decoding was needed (as per the OAuth 2.0 spec). The result is that client credentials containing `%`-prefixed sequences, whether valid sequences or not, are going to fail validation.
Remove the extra URL decoding. Add tests that ensure client credentials work with special characters in both the HTTP basic auth header and in the request body.
=> fix: double-decoding of client credentials in request body

authorize_request_handler.go, client.go, client_authentication.go, client_authentication_test.go, internal/key.go, token/jwt/jwt.go, token/jwt/jwt_test.go
Fixes: https://github.com/ory/fosite/issues/429
I added to `DefaultOpenIDConnectClient` a field `TokenEndpointAuthSigningAlgorithm` to be able to configure what `GetTokenEndpointAuthSigningAlgorithm` returns. I also cleaned some other places where there were assumptions about only RSA keys.
the changes.
=> feat: Added support for ES256 token strategy and client authentication

compose/compose_strategy.go
This is backwards incompatible change, but it allows one to set default issuer which seems to not be possible otherwise, despite being existing in the `DefaultJWTStrategy` struct.
the changes.
=> feat: Set default issuer in JWT tokens

README.md
Added some comments to the example code in `README.md` to explain the logic behind the empty session that appears in the token endpoint to hopefully avoid possible confusion such as in #448 and #256. Linking @aeneasr.
Just couple of lines of documentation and a reference to implementation of a real storage (SQL store) from ory/Hydra that should make it clearer why the empty session is needed (since example memory storage ignores it).
the changes.
=> docs: Add some comments to the example code explaining empty session

request.go, request_test.go
Minor improvement when looking at the code. `Get` returns just the first value.
A redo of https://github.com/ory/fosite/pull/454.
=> refactor: Copy all values when sanitizing

authorize_error_test.go, handler/oauth2/flow_authorize_code_token.go, handler/oauth2/flow_authorize_code_token_test.go, handler/oauth2/flow_client_credentials.go, handler/oauth2/flow_client_credentials_test.go, handler/oauth2/flow_refresh.go, handler/oauth2/flow_resource_owner.go, handler/oauth2/flow_resource_owner_test.go, handler/openid/flow_explicit_token.go, handler/openid/flow_refresh_token.go, handler/openid/flow_refresh_token_test.go
None.
This fixes a minor difference between Ory Fosite and the OAuth2.0 specification on errors to be returned.
According to https://tools.ietf.org/html/rfc6749#section-5.2 the error to be returned if a client requests a grant_type it's not allowed to is 'unauthorized_client'.
The current implementation returns 'invalid_grant'.
This PR changes that behaviour and also adds or adapts tests where needed.
the changes.
No.
=> fix: Align error returned when a grant_type was requested that's not allowed for a client.

.github/pull_request_template.md, .github/workflows/closed_references.yml, .github/workflows/labels.yml, .github/workflows/stale.yml, CONTRIBUTING.md
Updated repository templates to https://github.com/ory/meta/commit/1d3bdaf243c166ab2ed8a6de1c33ca728ff620a3.
=> chore: update repository template to 1d3bdaf2

CONTRIBUTING.md
Updated repository templates to https://github.com/ory/meta/commit/118b7850ed173d809e84acdf20fec1ff7273856f.
=> chore: update repository template to 118b7850

compose/compose.go
Reported the issue on the fosite-example repo [#32](https://github.com/ory/fosite-example/issues/32)
Currently revoke access or refresh token functionality is not working in the fosite-example repo because of the missing `OAuth2TokenRevocationFactory` as part of the OAuth provider initialisation so when loading the factories it didn't load and append the revoke handlers.
the changes.
No further comments, it's a tiny PR and self explanatory
=> fix: added missing factory to compose

errors.go, errors_test.go, handler/oauth2/flow_authorize_code_token.go, handler/oauth2/revocation.go, handler/oauth2/revocation_test.go
Not applicable
"revocation" is also spelled "revokation" in various place. Make it consistent - "revocation".
This changes some constant and/or variable names in the code, so I have made this a "refactor" PR.
the changes.
=> refactor: fix inconsistent spelling of revocation

handler/oauth2/flow_resource_owner_test.go
Not applicable
There is a typo of "authoriation_code" in a test. Fix it.
the changes.
=> test: fix typo of authorization_code in test

access_error.go, authorize_error.go, helper.go, helper_test.go
This is a followup to https://github.com/ory/fosite/pull/460.
This makes the escaping complete and not just partial. I think this is good enough because this code path should really never be called. But it does, we should do proper escaping which this now does.
the changes.
=> fix: Full JSON escaping

.github/workflows/closed_references.yml
Updated repository templates to https://github.com/ory/meta/commit/92ae8b93c03738d00573f229a412f9eac7a71a99.
=> chore: update repository template to 92ae8b93

.github/workflows/closed_references.yml, CONTRIBUTING.md, SECURITY.md
Updated repository templates to https://github.com/ory/meta/commit/6f3059720c2206a267a4e511cc149439a9a90906.
=> chore: update repository template to 6f305972

.github/workflows/closed_references.yml, .reference-ignore
Updated repository templates to https://github.com/ory/meta/commit/bf0b087e8893145e2067664515b1a75cb45fb92e.
=> chore: update repository template to bf0b087e

.github/workflows/closed_references.yml
Updated repository templates to https://github.com/ory/meta/commit/af2114f86f06ec1328d210c3034b405641a74a27.
=> chore: update repository template to af2114f8

audience_strategy.go, authorize_request_handler.go, authorize_request_handler_test.go, authorize_validators_test.go, handler/openid/validator.go
Making sure audience parsing in authorize flow is the [same as in access flow](https://github.com/ory/fosite/blob/master/access_request_handler.go#L75). Consistency.
Edit: I extended that with few other cases and made it consistent across the board. Also `stringx.Splitx` is not used anymore now because calling `RemoveEmpty` is equivalent (but does more).
the changes.
=> fix: Uniform audience parsing

handler/openid/strategy_jwt.go
This tripped me up. I didn't know that the returned claims will be modified in-place and that session should keep them stored and not simply return every time a new claims object.
Debugging this was hard.
the changes.
I must say I dislike in-place modification like this.
=> docs: Improve documentation for Session interface

introspection_response_writer.go, introspection_response_writer_test.go
One of our unit tests caught that after upgrade to latest fosite.
I introduced the regression with https://github.com/ory/fosite/pull/479 but existing fosite tests didn't catch it. The problem is that when returning `ErrInactiveToken` from `NewIntrospectionRequest` we now wrap underlying error, which can happen to be `ErrRequestUnauthorized`.
the changes.
=> fix: Always return non-error response for inactive tokens

handler/openid/flow_refresh_token.go
I found this during code review. I am not sure if it is correct. I could not find any test testing this. Even if I remove existing lines resetting `Nonce` and `ExpiresAt` nothing fails. So where is a test which would make sure that refreshed tokens do not have same JIT?
the changes.
=> fix: Resetting more ID token claims on refresh

access_request_handler.go, audience_strategy.go, audience_strategy_test.go, authorize_request_handler_test.go
Fixes #504.
Added `GetAudiences` helper function which tries to have current behavior and also support multiple/repeated audience parameters. If there are parameter is repeated, then it is not split by space. If there is only one then it is split by space. I think this is the best balance between standard/backwards behavior and allowing repeated parameter and allowing also URIs/audiences with spaces in them (which we probably all agree is probably not something anyone should be doing).
Also added `ExactAudienceMatchingStrategy` which is slightly more suitable to use for audiences which are not URIs. In [OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html) audience is described as:
> Audience(s) that this ID Token is intended for. It MUST contain the OAuth 2.0 client_id of the …
=> feat: Support passing repeated audience parameter

compose/compose_oauth2.go, handler/oauth2/introspector_jwt.go, handler/oauth2/introspector_jwt_test.go, handler/oauth2/strategy.go, handler/oauth2/strategy_jwt.go
Fixes: https://github.com/ory/fosite/issues/445
This makes it so that you can:
```
compose.OAuth2TokenRevocationFactory,
compose.OAuth2TokenIntrospectionFactory,
```
replace with:
```
compose.OAuth2StatelessJWTIntrospectionFactory,
```
and it just works. From looking at the code it looked to me like this was done long time ago where some other current interfaces were not yet around. So I modernized the code to use existing interfaces and removed a specialized interface used just by previous implementation.
All tests still pass. But I am not 100% sure if everything is correct (I have some doubts about original code). I also have few TODOs around the code so input there would be appreciated.
confirm that I got green …
=> fix: Modernized JWT stateless introspection

access_error_test.go, access_request_handler.go, audience_strategy.go, authorize_error_test.go, authorize_helper.go, authorize_request_handler.go, authorize_request_handler_oidc_request_test.go, client_authentication.go, client_authentication_jwks_strategy.go, errors.go, handler/oauth2/flow_authorize_code_auth.go, handler/oauth2/flow_authorize_implicit.go, handler/oauth2/flow_client_credentials.go, handler/oauth2/flow_refresh.go, handler/oauth2/flow_resource_owner.go, handler/oauth2/introspector.go, handler/oauth2/strategy_hmacsha.go, handler/openid/flow_hybrid.go, handler/openid/flow_implicit.go, handler/openid/strategy_jwt.go, handler/openid/validator.go, handler/pkce/handler.go, internal/introspector.go, introspection_request_handler.go, revoke_handler.go
Replace LF and quotes with `.` and `'` to match allowed and recommended character set defined in various RFCs.
Closes #525
the changes.
=> fix: only use allowed characters in error_description

client_authentication.go
Context was not always passed through.
the changes.
=> refactor: Use provided context

.github/pull_request_template.md, .github/semantic.yml, CONTRIBUTING.md
Updated repository templates to https://github.com/ory/meta/commit/781e8fb26afe90cedb50a939ad3fb6fa3798eefd.
=> chore: update repository template to 781e8fb2

authorize_request.go, authorize_request_test.go
the changes.
works.
appropriate).
=> fix: resolve regression

errors.go
#559
Rather than reusing the existing `errInvalidTokenFormatName` variable which is specific to an invalid token format, I've chosen to change the underlying string of `errTokenExpiredName`. This feels semantically correct as you refer to the error that's occurring (the token is expired) but the error code that's returned is the correct error code according to the spec. Happy to take an alternative approach if it's required.
the changes.
works.
appropriate).
I couldn't sign the CLA due to this issue
=> fix: Use correct error code for expired token

client_authentication.go, compose/compose.go, compose/config.go, fosite.go
#564 
- Add a `ClientAuthenticationStrategy` type to provide an extension point for custom client authentication methods
- Add `Fosite.DefaultClientAuthentication` as fosite's default and backward compatible client authentication strategy. Its content is 100% the current fosite's client authentication logic
- Add method `Fosite.WithDefaultClientAuthentication` to use fosite's default client authentication strategy
the changes.
- [ x] I have added tests that prove my fix is effective or that my feature
works.
- [x ] I have added necessary documentation within the code base (if …
=> feat: add client authentication strategy

handler/oauth2/flow_refresh.go, handler/oauth2/flow_refresh_test.go, integration/helper_setup_test.go, integration/refresh_token_grant_test.go, storage/memory.go
https://github.com/ory/hydra/issues/2022
This change makes `refresh_token` grant handler to check if we received `fosite.ErrInactiveToken` error from storage, which means there is an attempt to refresh access token using previously-used or revoked refresh token.
This is similar to what is done in Authorization Code Flow. 
the changes.
works.
appropriate).
These are changes just for fosite. I have another PR to make for hydra, so its persistent storage stops deleting refresh tokens from database on revocation. Instead it will mark them as inactive similar to what's done for auth …
=> feat: Token Reuse Detection

token/hmac/hmacsha.go
N/A
Update the messages and document with new algorithm name. The algorithm was changed earlier and it seems the references were not updated.
- [ x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [ x] I have read the [security policy](../security/policy).
- [x ] I confirm that this pull request does not address a security
the changes.
works.
- [x ] I have added necessary documentation within the code base (if
appropriate).
=> fix: sha alg name in error message and go doc

token/hmac/hmacsha.go, token/hmac/hmacsha_test.go
Left in previous commit.
N/A
One occurrence of non-standard algorithm name left in previous commit.
- [x ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [ x] I have read the [security policy](../security/policy).
- [ x] I confirm that this pull request does not address a security
the changes.
- [ x] I have added tests that prove my fix is effective or that my feature
works.
- [x ] I have added necessary documentation within the code base (if
appropriate).
=> fix: Change sha algorithm name acc to standard naming

go.mod, go.sum
I didn't open an issue, it's a minor version bump for a dependency.
This change bumps the minor version of the imported module `oleiade/reflections` from `v1.0.0` to `v1.0.1`.
There was an issue involving a change to the tags on the project that can result in transitive dependencies failing go checksums:
- https://github.com/golang/go/issues/44454
- https://github.com/oleiade/reflections/issues/14
Result:
```
verifying github.com/oleiade/reflections@v1.0.0/go.mod: checksum mismatch
downloaded: h1:rdFxbxq4QXVZWj0F+e9jqjDkc7dbp97vkRixKo2JR60=
go.sum:     h1:RbATFBbKYkVdqmSFtx13Bb/tVhR0lgOBXunWTZKeL4w=
SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download …
```
=> chore: update reflections mod past problem version

handler/oauth2/flow_authorize_code_auth.go, handler/oauth2/flow_authorize_code_auth_test.go
As discussed with@demonsthere, in the project's Slack Channel: https://ory-community.slack.com/archives/C012USDT5QQ/p1619102732018300
> I have a question / PR suggestion though regarding Fosite's implementation of the authorization code oauth2 flow (I couldn't find a Fosite-specific channel):
is it possible to omit the scope query param from the URL which contains the authorization code ? CF: https://github.com/ory/fosite/blob/master/handler/oauth2/flow_authorize_code_auth.go#L118
I have checked the RFC, it doesn't seem to require the scope parameter. I only see the code and state parameters as requirements
Our issue is that our scope list is quite long, and URL length does have a limitation on certain systems
Allow the omission of the `scope` query parameter in the authorization redirect …
=> feat: allow omitting scope in authorization redirect uri

docs/how-tos/client_credentials_grant.md
Issue #566 
This PR adds an initial *How To* to configure *Fosite* as an *OAuth2 Provider* to issue `RSA-JWT`  *access tokens* using [*Client Credentials Grant*](https://tools.ietf.org/html/rfc6749#section-1.3.4)
This is the first attempt to improve fosite's documentations with practical *how-tos* to customize it. Your input at this phase is very welcome :)
The idea would be to add multiple *how-to* files into the  `docs/how-tos/` folder, and once they are in a good shape, we link them in the `README.md`.
the changes.
works.
appropriate).
=> docs:add client credentials grant how-to

token/jwt/claims_id_token.go, token/jwt/claims_id_token_test.go
Not sure why was this there, but it makes no sense and there is no point in making ID tokens larger just to include an empty string.
the changes.
works.
appropriate).
=> fix: Do not include nonce in ID tokens when not used

access_request_handler.go, access_request_handler_test.go, access_response_writer.go, access_response_writer_test.go, authorize_request_handler.go, authorize_response_writer.go, context.go, introspection_request_handler.go, introspection_request_handler_test.go, revoke_handler.go, revoke_handler_test.go
https://github.com/ory/fosite/issues/537
This PR adds to current context various requests and response structs so that it is easier to access them in methods which otherwise do not get them as an argument. This allows easier implementation of different interfaces.
the changes.
works.
appropriate).
=> feat: Pass requests through context

token/jwt/claims_id_token.go, token/jwt/claims_id_token_test.go, token/jwt/claims_jwt.go, token/jwt/claims_jwt_test.go
This is a followup to https://github.com/ory/fosite/pull/522.
=> refactor: Generate claims in the same way

.github/workflows/oidc-conformity.yml, authorize_request_handler.go, authorize_request_handler_oidc_request_test.go, client_authentication.go, client_authentication_test.go, go.mod, go.sum, handler/oauth2/introspector_jwt.go, handler/oauth2/strategy_jwt.go, handler/openid/flow_explicit_token_test.go, handler/openid/flow_refresh_token_test.go, handler/openid/strategy_jwt.go, handler/openid/validator.go, token/jwt/claims_id_token.go, token/jwt/claims_jwt.go, token/jwt/header.go, token/jwt/jwt.go, token/jwt/jwt_test.go, token/jwt/key_test.go, token/jwt/map_claims.go, token/jwt/map_claims_test.go, token/jwt/token.go, token/jwt/token_test.go, token/jwt/validation_error.go
#514 
This pull request migrates from `jwt-go` to `go-jose`. The following are the key considerations for this transition:
- `go-jose` [does not support](https://github.com/square/go-jose/issues/185) `alg:none` therefore tests trying to check this functionality where removed
- `JWTStrategy` interface was kept almost identical to provide an easy migration, except for the following changes:
* `jwt.Token` struct type from `jwt-go` was replaced by a local and simplified type definition `Token` that covers all `fosite` use cases
*   `jwt.MapClaims` was replaced by a local copy of that data type
* `jwt.Claims` interface dependency to `jwt-go` was replaced by the local `MapClaims` struct type and not by another interface because it simplified the adaptation and `fosite` always type casted …
=> feat: transit from jwt-go to go-jose

token/jwt/claims_id_token.go, token/jwt/claims_id_token_test.go
#598 
Revert `auth_time` claim data type to `int64` in `id_token`. 
It was changed to `float64` in PR #595
the changes.
works.
appropriate).
In another PR timestamp claims for access tokens and id tokens can be transformed to `int64`. 
This is no longer a limitation since `fosite` now uses `go-jose`
=> fix: revert float64 auth_time claim

go.mod, go.sum, token/jwt/map_claims.go
#602
Use go-jose to decode JSON integers into int64.
the changes.
works.
appropriate).
Uses latest  go-jose `v2` version which included decoding JSON integers into int64.
Custom Unmarshal method is still needed because it is the only way to set go-jose decoding settings. Issue  [#353](https://github.com/square/go-jose/issues/353) address this limitation, if 
it gets resolved with an acceptable solution we can remove it
=> chore: upgrade go-jose to decode JSON numbers into int64

CONTRIBUTING.md
Updated repository templates to https://github.com/ory/meta/commit/4bad4b1b28491df76013a0a5c7da0b294a81ec7b.
=> chore: update repository template to 4bad4b1b

authorize_error.go, authorize_error_test.go, authorize_request_handler.go, authorize_write.go, compose/compose.go, compose/config.go, fosite.go, integration/authorize_form_post_test.go, response_handler.go
#591 
This is a *draft/preview* PR of the proposed change described in issue #591 
**Status**
* Main functionality is implemented
* Existing Unit tests pass
* Missing: 
* Add `ResponseModeHandler` in `compose.Config` package
* Add extra unit test 
* Document public interface and source code
the changes.
- [x ] I have added tests that prove my fix is effective or that my feature
works.
- [x ] I have added necessary documentation within the code base (if
appropriate).
=> feat: add ResponseModeHandler to support custom response modes

README.md, client.go, client_authentication.go, client_authentication_test.go, client_test.go, internal/client.go, introspection_request_handler.go, introspection_request_handler_test.go, storage/memory.go
Issue: #590
Discussed with: @aeneasr
The aim of this PR is to introduce support for rotation of client's secrets.
New interface is created that extends `fosite.Client` so as not to break compatibility of custom clients. The `fosite.DefaultClient` implements this interface by introducing `RotatedSecrets` field. When not set (nil), the functionality stays the same as before.
the changes.
works.
appropriate).
Detail of how the change above is utilized in the fosite code:
1. check regular (main, current) secret by using `GetHashedSecret` method
2. if 1. fails, try to see if provided …
=> feat: Add rotation support for client secrets

.github/workflows/stale.yml, CONTRIBUTING.md
Updated repository templates to https://github.com/ory/meta/commit/e424c0a0a2dd85c585c0be32e8ada257c3fe8021.
=> chore: update repository template to e424c0a0

token/jwt/claims_id_token.go, token/jwt/claims_id_token_test.go
This change makes `amr` claim follow the spec and be of an array type.
See: https://openid.net/specs/openid-connect-core-1_0.html#IDToken
My team noticed that when trying to use `amr` claim with Hydra. 
Will follow up with Hydra PR to add support for `amr` claim as it is being dropped right now if used. Related issue: https://github.com/ory/hydra/issues/1756
Previous change: https://github.com/ory/fosite/pull/401
the changes.
works.
appropriate).
This is breaking change, migration path is to wrap single values into the `[]string` slice and use a different field.
=> fix: Make `amr` claim an array to match the OIDC spec

authorize_error.go, authorize_error_test.go, authorize_write.go, authorize_write_test.go
`302 Found` behavior is not consistent across browsers and my team got into an issue with Safari maintaining `HTTP POST` across redirects after login through form. This results in a callback executed with `HTTP POST` instead of `HTTP GET`.
Changing redirects to `303 See Other` to force `HTTP GET`.
the changes.
works.
appropriate).
=> fix: force HTTP GET for redirect responses

authorize_helper.go, authorize_write.go, authorize_write_test.go
This patch reverts the encoding logic for the fragment of the redirect URL returned as part of the authorize response to what was the one before version `0.36.0`. In that version, the code was refactored and the keys and values of the fragment ceased to be url-encoded. This in turn reflected on all Ory Hydra versions starting from `1.9.0` and provoked a breaking change that made the parsing of the fragment impossible if any of the params contain a character like `&` or `=` because they get treated as separators instead of as text
Fixes #648
the changes. …
=> fix: url-encode the fragment of the redirect URL of the authorize response

client_authentication.go, client_authentication_test.go
The existing client authentication code treats an empty client_secret
query parameter to be equivalent to "none" authentication instead of
"client_secret_post."
This change updates the basic auth check to be consistent with this.
That is, an empty secret via the basic auth header is considered to
mean "none" instead of "client_secret_basic."
The "golang.org/x/oauth2" library probes for both methods of
authentication, starting with the basic auth header approach first.
As required, both client ID and secret are encoded in one header:
https://github.com/golang/oauth2/blob/ee480838109b20d468babcb00b7027c82f962065/internal/token.go#L174-L176
Since this code path is taken regardless of if the client is public
or confidential, without this change, it results in an error in the
fosite code. …
=> fix: empty client secret via basic auth header means "none" authn

handler/openid/flow_hybrid.go, handler/openid/flow_implicit.go, handler/openid/helper.go, handler/openid/helper_test.go
The defect is described in #630 along with the discussion.
1. `at_hash`: https://openid.net/specs/openid-connect-core-1_0.html#CodeIDToken
2. `c_hash`: https://openid.net/specs/openid-connect-core-1_0.html#HybridIDToken
the changes.
works.
appropriate).
There are two key changes:
1. Standardize computation of the hash across the different flows
2. Introduce `ComputeHash` that extracts the algorithm, if available, from the openid.Session header and computes the hash. It falls back to 256 key length to retain backward compatibility.
=> fix: [#630] Use the correct algorithm for at_hash and c_hash

compose/compose_oauth2.go, handler/oauth2/flow_resource_owner.go
This adds godoc deprecations to the compose.OAuth2ResourceOwnerPasswordCredentialsFactory and oauth2.ResourceOwnerPasswordCredentialsGrantHandler in order to clearly communicate the discouragement of the ROPC grant type to users implementing this library.
https://github.com/ory/fosite/issues/650#issuecomment-1100768170
the changes.
works.
appropriate).
No testing is applicable to this change as far as I am aware.
=> docs: add deprecation to communicate ropc discouragement

handler/oauth2/flow_authorize_code_token_test.go, handler/oauth2/flow_refresh_test.go, handler/oauth2/strategy_hmacsha.go, handler/oauth2/strategy_hmacsha_test.go, integration/refresh_token_grant_test.go
See https://github.com/ory/hydra/issues/2845
vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the
maintainers to push the changes.
=> feat: add `ory_at|pt|ac` prefixes to HMAC tokens

handler/openid/flow_explicit_token.go, handler/openid/flow_explicit_token_test.go
fosite has a bug which may prevent the `at_hash` claim from appearing in the ID token from an authcode grant. The bug is in the `PopulateTokenEndpointResponse` method of `OpenIDConnectExplicitHandler`. The bug will only impact systems which implement the storage interfaces by returning different struct instances.
There are two sessions at play the `PopulateTokenEndpointResponse` method of `OpenIDConnectExplicitHandler`:
1. The `requester` parameter contains a session. In typical usage of fosite, `requester` is created by a custom implementation of the token endpoint to represent the current request to the token endpoint. The token endpoint calls `NewAccessRequest`, which calls `HandleTokenEndpointRequest` on each token endpoint handler. The `AuthorizeExplicitGrantHandler`’s implementation …
=> Fix bug which prevents the `at_hash` claim from appearing in the ID token from an authcode grant for some storage implementations

go.mod, go.sum, integration/client_credentials_grant_test.go
=> test: fix assertions

handler/openid/strategy_jwt.go, token/jwt/claims_id_token.go, token/jwt/header.go
This change adds json mappings to `DefaultSession` type and its contents to use in enriching the refresh webhook in Hydra here https://github.com/ory/hydra/pull/3204
This is the same as https://github.com/ory/fosite/pull/687 but for `master` to benefit Hydra v2.
=> feat: add json mappings to default session and its contents

handler/oauth2/revocation.go, handler/oauth2/revocation_test.go
When TokenRevocationStorage.GetRefreshTokenSession return fosite.ErrInactiveToken, handle fosite.ErrInactiveToken.
related to: https://github.com/ory/fosite/issues/709
(Sorry, it may not be a related issue.)
=> fix: when TokenRevocationStorage.GetRefreshTokenSession return fosite.ErrInactiveToken, handle fosite.ErrInactiveToken

storage/memory.go
fix: The example storage is missing the initialization of the PARsessions. So when using that example storage with the PAR endpoints the application will panic with an error that it tried to assign something to a nil pointer/map
This fix initializes the par map.
=> fix: missing init of the par sessions in the example store

handler/oauth2/flow_refresh.go
Fix server error of handling refresh token reuse.
When refresh token requests come same time, some times server error is occurred. (related to https://github.com/ory/hydra/pull/3207 )
This error is client matter. So I want to fix it as client error.
```json
{
"error": {
"debug": "invalid_request",
"reason": "",
"status": "Internal Server Error",
"status_code": 500
}
}
```
<details>
<summary>StackTrace(debug mode)</summary>
```
github.com/ory/x/errorsx.WithStack
/go/pkg/mod/github.com/ory/x@v0.0.368/errorsx/errors.go:38
github.com/ory/fosite/handler/oauth2.(*RefreshTokenGrantHandler).handleRefreshTokenEndpointStorageError
/go/pkg/mod/github.com/ory/fosite@v0.42.3-0.20220729111320-05d71b23559c/handler/oauth2/flow_refresh.go:241
github.com/ory/fosite/handler/oauth2.(*RefreshTokenGrantHandler) …
```
=> fix: fix server error of handling refresh token reuse

token/jwt/header.go, token/jwt/token.go, token/jwt/token_test.go
First, thank you for all your work on this library! 🙇 
We are implementing [RFC9068](https://datatracker.ietf.org/doc/rfc9068/) and during that we found the following issue: the JWT header's `typ` parameter is implicitly set to "JWT" inside token.go by the the `unsignedToken` function. Also the `ToMap` function filters out the `typ` as well and unfortunately it cannot be changed from the Session for example. And based on https://datatracker.ietf.org/doc/html/rfc9068#section-2.1-3 the `typ` must be set to `at+jwt`. 
This PR adds the ability to set the `typ` parameter from the `jwt.Headers` and when the `typ` is not set explicitly then the `typ` will be set to "JWT".
I confirm that I got approval (please contact …
=> feat: add the ability to set jwt header type

session.go, session_test.go
Remove a redundant check for whether an element is present in a map. Since we return the zero value of a `time.Time` anyway, it's simpler to use the single return value version to access the map.
I have not added any documentation or tests for this since it is such a small fix.
=> fix: remove redundant map access

.github/workflows/format.yml, .github/workflows/licenses.yml, .github/workflows/oidc-conformity-master.yml, .github/workflows/oidc-conformity.yml, .github/workflows/test.yml, client_authentication.go, config.go, config_default.go, handler/rfc7523/handler.go, handler/rfc7523/handler_test.go
Part of https://github.com/ory/network/issues/335
=> feat: support multiple token URLs

handler/openid/flow_explicit_token.go, handler/openid/flow_explicit_token_test.go, handler/openid/storage.go, storage/memory.go
Fixes https://github.com/ory/fosite/issues/790. Please see description and comments in https://github.com/ory/fosite/issues/790 for more information about why this is a necessary and safe change.
```
Remove deprecation of `DeleteOpenIDConnectSession` storage interface function and call it during
authorization code exchange. This function was not previously called. Implementors of the openid
storage interface who which to preserve the old behavior should implement this function as a
no-op which returns `nil`.
```
Fixes #790.
=> fix: call DeleteOpenIDConnectSession during successful authcode exchange

client.go
`client_secret_jwt` is not really supported.
=> fix: do not list client_secret_jwt as supported

request.go, request_test.go
=> fix: pass standard params to storage

authorize_helper.go, authorize_helper_test.go
I think this was missed when `ctx` was added around. Now it cannot be used for `RedirectSecureChecker` config.
=> fix: add missing ctx argument to IsRedirectURISecureStrict

handler/pkce/handler.go, handler/pkce/handler_test.go
This fixes an issue where the PKCE sessions are generated needlessly which also leads to errors in some circumstances.
Fixes #743 
=> fix(pkce): session generated needlessly

authorize_helper.go, authorize_helper_whitebox_test.go
See: https://github.com/ory/fosite/commit/44fd2cc2356954292d435e45712624d4145debc7#r138568658
=> fix: use stdlib to check loopback address

go.mod, go.sum, tools.go
This was added in 452f377288, but doesn't appear to be used anywhere.
=> chore: remove unneeded dependency github.com/ecordell/optgen

compose/compose_strategy.go, handler/oauth2/strategy_hmacsha.go, handler/oauth2/strategy_hmacsha_prefixed.go, handler/oauth2/strategy_hmacsha_test.go, handler/openid/flow_hybrid_test.go, handler/pkce/handler_test.go, integration/helper_setup_test.go
BREAKING CHANGES: Going forward, the `HMACSHAStrategy` requires a `BaseHMACSHAStrategy`. Here is how to upgrade it:
```patch
var hmacshaStrategy = HMACSHAStrategy{
-	Enigma: &hmac.HMACStrategy{Config: &fosite.Config{GlobalSecret: []byte("foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar")}},
-	Config: &fosite.Config{
-		AccessTokenLifespan:   time.Hour * 24,
-		AuthorizeCodeLifespan: time.Hour * 24,
+	BaseHMACSHAStrategy: &BaseHMACSHAStrategy{
+		Enigma: &hmac.HMACStrategy{Config: &fosite.Config{GlobalSecret: []byte("foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar")}},
+		Config: &fosite.Config{
+			AccessTokenLifespan:   time.Hour * 24,
+			AuthorizeCodeLifespan: time.Hour * 24,
+		},
},
}
```
- ~[ ] I have referenced an issue containing the design document if my change introduces a new …
=> refactor: split HMAC SHA strategy

introspection_response_writer.go, introspection_response_writer_test.go
A simple fix. For inactive tokens there were no headers.
=> fix: WriteIntrospectionResponse should always issue headers

token/jwt/jwt.go, token/jwt/jwt_test.go
It is harder to validate generated JWTs because currently they do not include a key ID in the header. Even when key ID exists in the JWK used for signing. The reason is that Fosite currently removes this metadata information, but it is not necessary to remove it, our signing library uses it and knows how to use JWKs, even more, it adds key ID automatically if it is available and provided with a JWK.
=> fix: pass JWK for singing so that KeyID is set in JWTs

errors.go
`github.com/pkg/errors`'s `New` records a stack trace but for sentinel errors you do not want to record a stack trace of Go initialization. One should return `errorsx.WithStack(ErrInvalidatedAuthorizeCode)` to attach a stack trace with the error.
=> fix: do not store stacktrace in sentinel errors

go.mod, token/hmac/bytes.go, token/hmac/bytes_test.go, token/hmac/hmacsha.go, token/hmac/hmacsha_test.go
=> chore: minor improvements to readability and updated code style

scope_strategy.go
=> fix: remove duplicated matcher split

errors.go, handler/oauth2/flow_refresh.go
See https://github.com/ory-corp/cloud/issues/7311
=> chore: make serialization error wrappable

introspection_request_handler.go, introspection_response_writer.go, oauth2.go
There are some invalid links in the documentation, which can result in the user writing this PR and forgetting what they were working on in the first place.
see above
- [no] I have referenced an issue containing the design document if my change introduces a new feature.
- [no] I have read the [security policy](../security/policy).
- [+] I confirm that this pull request does not address a security vulnerability. 
- [] I have added tests that prove my fix is effective or that my feature works.
`/search/...` should be `/html/...`
=> docs: inconsistent RFC links in documentation

storage/memory.go
We use memory store for tests and we noticed race conditions failing those tests occasionally. It looks like locking was not correct in memory store.
=> fix: proper locking of memory store
